### ISSUE TITLE
Taking counterfactual samples through to gex to rank genes

### ISSUE THREAD

**Issue by adamgayoso** [YosefLab/mrvi#20]
which genes are changing the most for counterfactual samples

**Comment by PierreBoyeau** [comment]
A reasonable method could be the following

Inputs: 
- some adata for a subset of cells, characterizing a cell-type
- a sample metadata key (assumed binary)

Algorithm: 
For each cell:
1. Compute decoded normalized gene expression vectors $h_1, ... h_S$
2. Compute the effect size for each gene characterizing differences in expression

We obtain an effect size matrix of shape # of cells * # of genes. We can then sort the genes by their mean effect size (in absolute value)
