### ISSUE TITLE
Produce user-guide and tutorial

### ISSUE THREAD

**Issue by PierreBoyeau** [YosefLab/mrvi#96]

**Comment by justjhong** [comment]
Draft of user guide: [MrVI User Guide.md](https://github.com/YosefLab/mrvi/files/15154943/MrVI.User.Guide.md) @martinkim0 to add to staging branch when we are ready to submit.

**Comment by justjhong** [comment]
tracked here: https://github.com/scverse/scvi-tools/pull/2761
